### PR TITLE
a

### PR DESCRIPTION
**Pull request by mercedesov**

### CODE REVIEW

**Comment by AndranikAdyan** [comment]
You don't have the any files.

**Comment by LusineSahakya** [comment]
Uploaded not correctly, please recheck your project.

**Comment by mercedesov** [comment]
> You don't have the any files.

Please check "check" branch: mercedesov/madlibz:check it has the file madlibz.py in it

**Comment by mercedesov** [comment]
> Uploaded not correctly, please recheck your project.

Please check "check" branch: mercedesov/madlibz:check it has the file madlibz.py in it

**Comment by AndranikAdyan** [comment]
> > You don't have the any files.
> 
> Please check "check" branch: mercedesov/madlibz:check it has the file madlibz.py in it

First of all, you could write
Number = input("Enter a number:")
time_measure = input("Enter time measure:")
instead of
print("Enter a number:")
number = input()
Print()
time_measure = input()

If I’m not mistaken, the assignment said that you can only use the print() and input() functions and the “random” library, but you have the int() function in your code. I think you should replace the int() function (write a similar one yourself)

**Comment by LusineSahakya** [comment]
Everything is ok.

**Comment by AndranikAdyan** [comment]
Done!

**Pull request merged**
